version: "3"
services:
  web:
    image: eegor/greycode:dev1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "$HOME/greycode/redis:/data"
    deploy:
    command: redis-server --appendonly yes
    networks:
      - webnet 
networks:
  webnet:
